In [9]:
import numpy as np
import pandas as pd

csv_file_path = 'E:\\anaconda3\\anaconda files\\lab3\\NationalNames.csv'
try:
    df = pd.read_csv(csv_file_path)    
except FileNotFoundError:
    print(f"File not found: {csv_file_path}")
    
display(df.head(8))

   Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746
5   6   Margaret  1880      F   1578
6   7        Ida  1880      F   1472
7   8      Alice  1880      F   1414